### ISSUE TITLE
(RuntimeError) Invalid FieldReference: `{[rule][description]}`

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#100]
HI, im trying to give this project a go in our pre-prod environment. Setup from scratch ELK installed on ubuntu 1804 - had lots of issues on the way until get to the below error: mainly related to Logstash permissions, settings etg. I have read and learn on the way so much but I need help troubleshooting this:
I run the command 
sudo /usr/share/logstash/bin/logstash  -f /etc/logstash/conf.d/ --path.settings=/etc/logstash --log.level=debug
 Logstash does the job until error. 

Any helpl and guidance appreciated, cheers!

020-04-23T00:26:19,645][ERROR][org.logstash.execution.WorkerLoop][main] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.RuntimeError: (RuntimeError) Invalid FieldReference: `{[rule][description]}`
        at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.include?(org/logstash/ext/JrubyEventExtLibrary.java:129) ~[logstash-core.jar:?]
        at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_translate_minus_3_dot_2_dot_3.lib.logstash.filters.single_value_update.test_for_inclusion(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/single_value_update.rb:29) ~[?:?]
        at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_translate_minus_3_dot_2_dot_3.lib.logstash.filters.translate.filter(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/translate.rb:191) ~[?:?]
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143) ~[?:?]
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162) ~[?:?]
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1814) ~[jruby-complete-9.2.9.0.jar:?]
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159) ~[?:?]
        at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115) ~[logstash-core.jar:?]
        at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262) ~[?:?]
warning: thread "[main]>worker0" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: org.jruby.exceptions.RuntimeError: (RuntimeError) Invalid FieldReference: `{[rule][description]}`
        at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)
        at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262)
        at org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)
        at java.lang.Thread.run(java/lang/Thread.java:834)
Caused by: org.jruby.exceptions.RuntimeError: (RuntimeError) Invalid FieldReference: `{[rule][description]}`
        at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.include?(org/logstash/ext/JrubyEventExtLibrary.java:129)
        at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_translate_minus_3_dot_2_dot_3.lib.logstash.filters.single_value_update.test_for_inclusion(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/single_value_update.rb:29)
        at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_translate_minus_3_dot_2_dot_3.lib.logstash.filters.translate.filter(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/translate.rb:191)
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143)
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1814)
        at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)
        at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115)
        at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262)
[2020-04-23T00:26:19,666][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2020-04-23T00:26:19,667][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2020-04-23T00:26:19,800][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>java.lang.IllegalStateException: org.jruby.exceptions.RuntimeError: (RuntimeError) Invalid FieldReference: `{[rule][description]}`, :backtrace=>["org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)", "java.lang.Thread.run(java/lang/Thread.java:834)"]}
[2020-04-23T00:26:19,808][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
[2020-04-23T00:26:19,814][DEBUG][logstash.agent           ] 2020-04-23 00:26:19 +0200: Listen loop error: #<NoMethodError: undefined method `first' for nil:NilClass>
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.3-java/lib/puma/server.rb:384:in `handle_servers'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.3-java/lib/puma/server.rb:356:in `block in run'
[2020-04-23T00:26:19,814][DEBUG][logstash.agent           ] Error in reactor loop escaped: closed stream (IOError)

**Comment by revere521** [comment]
Looks like this the same as #99  - the 35-rules-desc.conf can be removed for now, and that will solve the error

**Comment by a3ilson** [comment]
Please download the latest 35-rules-desc.conf to correct this issue.  Additionally, if not utilizing the rule description, you may omit without issues.

**Comment by myrsecurity** [comment]
Removing  35-rules-desc.conf from the directory made it work. 

Im having other issues right now, not sure what exact entity is running logstashs (root, logstash, other users ) as how can to set reading the right configurational files
now haing this isssue: on kibana --> logs stream: 

11:45:57.046
failed to find message
11:45:57.048
failed to find message

**Comment by revere521** [comment]
you may want to open a new issue to describe clearly what you are experiencing
