### ISSUE TITLE
Anyone using this with XPACK Security? 

### ISSUE THREAD

**Issue by fastxl** [pfelk/pfelk#150]
Anyone have a config with XPACK Security? I have been trying to get it setup on a single node "test". I can get the Kibana and Elasticsearch setup and working but I am having trouble with Logstash. Would I need to add a user name and password to the 01-inputs.conf?

**Comment by rrosson** [comment]
You will need to add your auth to to 50-outputs.conf file located in /etc/logstash/conf.d

Hope this helps

**Comment by fastxl** [comment]
@rrosson Thanks for the tip. So here is my 50-outputs.conf

```
# 50-outputs.conf
output {
  elasticsearch {
    id => "pf"
    hosts => ["http://localhost:9200"]
    user => "logstash_system"
    password => "MyPasswordHere"
   #index => "pf-%{+YYYY.MM.dd}"
    manage_template => true
    template => "/etc/logstash/conf.d/templates/pf-geoip-template.json"
    template_name => "pf-geoip"
    template_overwrite => true
    ilm_rollover_alias => "pf"
    ilm_policy => "pf-ilm-policy"
  }
}

```
I added 
`user =>` 
and 
`password =>`
 when I restart logstash `
systemctl restart logstash.service` 
I get this in the log 
`[2020-08-10T13:35:29,140][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Got response code '401' contacting Elasticsearch at URL 'http://localhost:9200/_xpack'"}
`
When I try to stop logstash 
`systemctl stop logstash.service`
It never successfully stops and when I check the status it shows me this 
`Active: deactivating (stop-sigterm) since Mon 2020-08-10 13:36:05 CDT; 1min 29s ago`
The only way I have been able to reconfig logstash at this point is by rebooting the machine.

**Comment by a3ilson** [comment]
@fastxl 
In addition to your outputs, you also need to amend both the kibana.yml and logstash.yml

Kibana.yml (Lines 43-44)
```
elasticsearch.username: "elastic"
elasticsearch.password: "changeme"
```

Logstash.yml (Lines 256-259)
```
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: "localhost:9200"
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "changeme"

```

**Comment by fastxl** [comment]
I have that set. Getting this error in the logstash-plain.log
```
[2020-08-11T06:52:44,217][ERROR][logstash.outputs.elasticsearch][main] Failed to install template. {:message=>"Got response code '403' contacting Elasticsearch at URL 'http://localhost:9200/_template/pf-geoip'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:341:in `exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:346:in `template_exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:82:in `template_install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/template_manager.rb:28:in `install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/template_manager.rb:16:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:205:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:49:in `block in setup_after_successful_connection'"]}
[2020-08-11T06:52:44,365][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-City.mmdb"}
[2020-08-11T06:52:44,365][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:341:in `exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:359:in `rollover_alias_exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:91:in `maybe_create_rollover_alias'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:10:in `setup_ilm'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:50:in `block in setup_after_successful_connection'"]}
[2020-08-11T06:52:44,387][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

**Comment by a3ilson** [comment]
Update your 50-outputs.conf as follows:

```
# 50-outputs.conf
output {
  elasticsearch {
    id => "pf"
    hosts => ["http://localhost:9200"]
    index => "pf-%{+YYYY.MM.dd}"
    manage_template => true
    template => "/etc/logstash/conf.d/templates/pf-geoip-template.json"
    template_name => "pf-geoip"
    template_overwrite => false
    user => “username”
    password => “changeme”
  }
}
```

**Comment by fastxl** [comment]
Changed it and getting this error
`Aug 11 09:04:47 elk-home logstash[1039]: [2020-08-11T09:04:47,362][ERROR][logstash.outputs.elasticsearch][main][pf] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"http://localhost:9200/_bulk"}`

**Comment by fastxl** [comment]
Playing around a little more I decided to change the user name from `logstash_system` to `elastic` and it now seems to work. Here is what I have in the 50-outputs.conf
```
# 50-outputs.conf
output {
  elasticsearch {
    id => "pf"
    hosts => ["http://localhost:9200"]
    #index => "pf-%{+YYYY.MM.dd}"
    manage_template => true
    template => "/etc/logstash/conf.d/templates/pf-geoip-template.json"
    template_name => "pf-geoip"
    template_overwrite => false
    user => "elastic"
    password => "MyElasticPassword"
    ilm_rollover_alias => "pf"
    ilm_policy => "pf-ilm-policy"
  }
}
```

Not sure why the username change worked.  I need to learn more about the users and roles. For now it's working.

**Comment by fktkrt** [comment]
Maybe your users got mixed up in the process? What users do you have and with what privileges?
To set up auth for Logstash, I can recommend this guide: https://www.elastic.co/guide/en/logstash/master/ls-security.html

**Comment by a3ilson** [comment]
@fastxl - are you good-to-go?

**Comment by a3ilson** [comment]
Issue appears to be resolved.

**Comment by fastxl** [comment]
Sorry for the delay. Yes it was resolved and thanks to all for the help.
