### ISSUE TITLE
pfelk-install-5.5.0.sh, dashboards for import

### ISSUE THREAD

**Issue by MandyBaxter** [pfelk/pfelk#167]
pfelk-install-5.5.0.sh _almost_ works on a clean install of ubuntu server 20.04.1 on vbox. Issue is, at 6b. Import dashboards, no dashboards are found. 

**To Reproduce**
1. ./pfelk-install-5.5.0.sh
2. Follow https://github.com/3ilson/pfelk/blob/master/install/configuration.md
3. Get to step 6.b
4. See no dashboards to import

**Screenshots**

**Firewall System (please complete the following information):**
pfSense 2.4.5-RELEASE-p1 
Nothing special in my use case. Just plain vanilla with some pfBlockerNG rules.
 
**Operating System (please complete the following information):**
Linux 5.4.0-42-generic x86_64
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 **Installation method (manual, ansible-playbook, docker, script):**
pfelk-install-5.5.0.sh
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
elasticsearch 7.9.0 
 logstash 1:7.9.0-1
kibana 7.9.0

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:51) [elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:414) [elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710) [elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.0.jar:7.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-08-29T17:52:07,384][INFO ][o.e.c.r.a.AllocationService] [elk] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana_task_manager_1][0]]]).
[2020-08-29T17:52:15,702][INFO ][o.e.c.m.MetadataIndexTemplateService] [elk] adding template [.management-beats] for index patterns [.management-beats]

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
[2020-08-29T17:52:41,450][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>3.45}
[2020-08-29T17:52:41,511][INFO ][logstash.inputs.beats    ][main] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2020-08-29T17:52:41,582][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2020-08-29T17:52:41,731][INFO ][logstash.inputs.udp      ][main][c722e7ad29b32a2b76e842f61e129378c129b5d84cf4e0a10d38f4487a50b52e] Starting UDP listener {:address=>"0.0.0.0:5140"}
[2020-08-29T17:52:41,801][INFO ][logstash.inputs.udp      ][main][fab3ff0dedf16ef86d711131d4dcb6a309987fb1bfc5ca86d9a7c6f19fb9efe6] Starting UDP listener {:address=>"0.0.0.0:5145"}
[2020-08-29T17:52:42,058][INFO ][org.logstash.beats.Server][main][9ef91bee017f10756a1f4024c6e48b7e8bbcb3901a996bfb6db52695535d1175] Starting server on port: 5044
[2020-08-29T17:52:42,083][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2020-08-29T17:52:42,138][INFO ][logstash.inputs.udp      ][main][c722e7ad29b32a2b76e842f61e129378c129b5d84cf4e0a10d38f4487a50b52e] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2020-08-29T17:52:42,198][INFO ][logstash.inputs.udp      ][main][fab3ff0dedf16ef86d711131d4dcb6a309987fb1bfc5ca86d9a7c6f19fb9efe6] UDP listener started {:address=>"0.0.0.0:5145", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2020-08-29T17:52:42,692][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

 - Kibana logs (`journalctl -u kibana.service`)

Aug 29 19:07:50 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:50Z","tags":["info","plugins","taskManager","taskManager"],"pid":1535,"message":"TaskManager is ident
ified by the Kibana UUID: cb11d5a8-80ad-4c80-bd69-938375eb37c2"}
Aug 29 19:07:50 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:50Z","tags":["info","plugins","watcher"],"pid":1535,"message":"Your basic license does not support wa
tcher. Please upgrade your license."}
Aug 29 19:07:50 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:50Z","tags":["info","plugins","crossClusterReplication"],"pid":1535,"message":"Your basic license doe
s not support crossClusterReplication. Please upgrade your license."}
Aug 29 19:07:50 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:50Z","tags":["info","plugins","monitoring","monitoring","kibana-monitoring"],"pid":1535,"message":"St
arting monitoring stats collection"}
Aug 29 19:07:51 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:51Z","tags":["status","plugin:kibana@7.9.0","info"],"pid":1535,"state":"green","message":"Status chan
ged from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Aug 29 19:07:51 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:51Z","tags":["status","plugin:elasticsearch@7.9.0","info"],"pid":1535,"state":"yellow","message":"Sta
tus changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Aug 29 19:07:51 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:51Z","tags":["status","plugin:elasticsearch@7.9.0","info"],"pid":1535,"state":"green","message":"Stat
us changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Aug 29 19:07:51 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:51Z","tags":["status","plugin:xpack_main@7.9.0","info"],"pid":1535,"state":"green","message":"Status 
changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Aug 29 19:07:51 elk kibana[1535]: {"type":"log","@timestamp":"2020-08-30T00:07:51Z","tags":["status","plugin:monitoring@7.9.0","info"],"pid":1535,"state":"green","message":"Status 
changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[error.pfelk.log](https://github.com/3ilson/pfelk/files/5146139/error.pfelk.log)

**Comment by a3ilson** [comment]
Thanks!  I updated the links within step 6b - apologize for the inconvenience. 

Please close, if this corrects the issue.
