### ISSUE TITLE
Unable to get any dashboards working

### ISSUE THREAD

**Issue by an0wak** [pfelk/pfelk#208]
**Describe the bug**
I have installed new instances of Debian and Ubuntu and tried installing via the script and manually.
Everything seems to go smoothly and successfully but after importing all the templates and dashboards, I am unable to see dashboard information.
They come up with Error - esaggs > Bad Request.
The firewall and squid logs are hitting the pelk host.

**To Reproduce**
Steps to reproduce the behaviour:
Install clean Debian 10.6 or Ubuntu (mini.iso) 18.04.5 LTS
Follow the guide using the scripted installer or manual install. Follow the configurations.
Using manual I ignore optional sections and during configuration ignore dashboards for Unbound,Suricata,HAProxy and Snort.
I only require Firewall and Squid.

**Screenshots**
![Dasherror1](https://user-images.githubusercontent.com/74270857/98787887-30d43b00-2454-11eb-9c7f-e7de8aecb22e.png)
![DashError2](https://user-images.githubusercontent.com/74270857/98787903-35005880-2454-11eb-8203-1a055926e83e.png)
![DashError3](https://user-images.githubusercontent.com/74270857/98787911-3762b280-2454-11eb-94d6-012e74064e89.png)
![OGPSLSUNIe](https://user-images.githubusercontent.com/74270857/98787919-3af63980-2454-11eb-9d54-f87734b6f65e.png)

**Firewall System (please complete the following information):**
- OPNsense 20.7.4-amd64
- FreeBSD 12.1-RELEASE-p10-HBSD
- LibreSSL 3.1.4

**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -srm
Linux 4.19.0-12-amd64 x86_64

 **Installation method (Tried both manual and scripted)
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
elasticsearch                           7.9.3                     amd64                  Distributed RESTful search engine built for the cloud
logstash                                  1:7.9.3-1                 all                       An extensible logging pipeline
 kibana                                    7.9.3                     amd64                     Explore and visualize your Elasticsearch data

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 
[2020-11-11T16:45:03,444][INFO ][o.e.n.Node               ] [vlog] started
[2020-11-11T16:45:03,938][INFO ][o.e.l.LicenseService     ] [vlog] license [46758ea3-52e8-4d51-b68b-fad5f26f0d9b] mode [basic] - valid
[2020-11-11T16:45:03,940][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [vlog] Active license is now [BASIC]; Security is disabled
[2020-11-11T16:45:03,953][INFO ][o.e.g.GatewayService     ] [vlog] recovered [9] indices into cluster_state
[2020-11-11T16:45:04,132][WARN ][r.suppressed             ] [vlog] path: /.kibana_task_manager/_count, params: {index=.kibana_task_manager}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$0(AbstractSearchAsyncAction.java:223) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$2.doRun(AbstractSearchAsyncAction.java:288) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-11-11T16:45:04,127][WARN ][r.suppressed             ] [vlog] path: /.kibana/_count, params: {index=.kibana}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$0(AbstractSearchAsyncAction.java:223) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$2.doRun(AbstractSearchAsyncAction.java:288) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-11-11T16:45:05,699][INFO ][o.e.c.r.a.AllocationService] [vlog] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[pfelk-firewall-2020.11.11][0]]]).
[2020-11-11T16:45:11,417][INFO ][o.e.c.m.MetadataIndexTemplateService] [vlog] adding template [.management-beats] for index patterns [.management-beats]
[2020-11-11T17:07:08,463][INFO ][o.e.c.m.MetadataIndexTemplateService] [vlog] adding template [.management-beats] for index patterns [.management-beats]
[2020-11-11T17:40:34,075][INFO ][o.e.c.m.MetadataCreateIndexService] [vlog] [pfelk-unbound-2020.11.11] creating index, cause [auto(bulk api)], templates [pfelk-geoip, pfelk], shards [1]/[1]
[2020-11-11T17:40:34,257][INFO ][o.e.c.m.MetadataMappingService] [vlog] [pfelk-unbound-2020.11.11/Edx9BsYRQwubuJoX4VPpzA] update_mapping [mappings]

- Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)

[2020-11-11T16:45:49,115][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2020-11-11T16:45:49,110][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2020-11-11T16:45:49,131][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2020-11-11T16:45:49,243][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,279][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,227][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,288][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,213][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,312][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-11-11T16:45:49,333][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}

- Kibana logs (`journalctl -u kibana.service`)
Nov 11 19:06:30 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:30Z","tags":[],"pid":1509,"method":"post","statusCode":400,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:06:31 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:31Z","tags":[],"pid":1509,"method":"delete","statusCode":200,"req":{"url":"/internal/search/es/FkxsLWIwLU1FU3ZpZzkzNDFEc0pBSHccUmc3TXdVajZRcG1BOHlMSTBDW
Nov 11 19:06:31 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:31Z","tags":[],"pid":1509,"method":"delete","statusCode":200,"req":{"url":"/internal/search/es/Fi1oLWNRb3poVEtlX2d1U0szOFB0aVEcUmc3TXdVajZRcG1BOHlMSTBDW
Nov 11 19:06:31 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:31Z","tags":[],"pid":1509,"method":"delete","statusCode":200,"req":{"url":"/internal/search/es/Fm1sUHhRZGw4Uk5DTjM3YjJscTBkc2ccUmc3TXdVajZRcG1BOHlMSTBDW
Nov 11 19:06:31 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:31Z","tags":[],"pid":1509,"method":"delete","statusCode":200,"req":{"url":"/internal/search/es/Fm5RQzJnM1JHUjYtWF9zdW5BNVdwT2ccUmc3TXdVajZRcG1BOHlMSTBDW
Nov 11 19:06:31 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:31Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:06:36 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:06:36Z","tags":[],"pid":1509,"method":"get","statusCode":200,"req":{"url":"/34038/bundles/plugin/kibanaLegacy/af7ae505a9eed503f8b8e6982036873e.woff2","meth
Nov 11 19:07:53 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:07:53Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"servername:5601","con
Nov 11 19:17:52 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:17:52Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"servername:5601","con
Nov 11 19:19:59 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:19:59Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"servername:5601","con
Nov 11 19:26:35 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:34Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"servername:5601","con
Nov 11 19:26:36 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:36Z","tags":[],"pid":1509,"method":"get","statusCode":200,"req":{"url":"/ui/favicons/favicon.ico","method":"get","headers":{"host":"servername:5601","co
Nov 11 19:26:36 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:36Z","tags":[],"pid":1509,"method":"get","statusCode":200,"req":{"url":"/ui/favicons/favicon.ico","method":"get","headers":{"host":"servername:5601","co
Nov 11 19:26:42 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:42Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/saved_objects/_bulk_get","method":"post","headers":{"host":"servername:560
Nov 11 19:26:42 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:42Z","tags":[],"pid":1509,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/_find?fields=title&per_page=10000&type=index-pattern","method
Nov 11 19:26:43 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:43Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/saved_objects/_bulk_get","method":"post","headers":{"host":"servername:560
Nov 11 19:26:43 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:43Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:26:44 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:44Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:26:46 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:45Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:26:47 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:26:47Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/internal/search/es","method":"post","headers":{"host":"servername:5601","conne
Nov 11 19:27:25 vlog kibana[1509]: {"type":"response","@timestamp":"2020-11-11T08:27:24Z","tags":[],"pid":1509,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"servername:5601","con

**Comment by a3ilson** [comment]
@an0wak - Can you provide a screen shot of Stack Management>>Index Management--Index Templates
![Capture](https://user-images.githubusercontent.com/16884679/98828545-32771200-2406-11eb-88c9-7f680c0ea8ca.PNG)

**Comment by an0wak** [comment]
Hi, I noticed some issues with shards under the elasticsearch.logs in regards to Java ... and had tired many attempts to fix it with no luck. Given so many changes I decided to blown it all away and run a clean minimal install of Debian and use the scripted install. all messages came back successful. Looking at the logs they seem OK with no "standing out" errors - yet I still get the error under the dashboard panels. I read other post about the amount of data required.... how much is that?

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by an0wak** [comment]
Added the clean installation log and outputs.
[pelk-log.txt](https://github.com/3ilson/pfelk/files/5526838/pelk-log.txt)

Funny thing is that the previous version seemed to work... think it was using v5.5 dashboards.

By the way excellent project ... hopefully I can get it working again - cheers!

**Comment by a3ilson** [comment]
@an0wak - Did you complete [these steps](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) and specifically steps 2 and 3?

**Comment by an0wak** [comment]
Hi Andrew,
Yes I ran through those steps. Question, are all required if I only want to view Firewall and Squid information.
I have tried with all and just the required ones.. still get the error.

![image](https://user-images.githubusercontent.com/74270857/98880461-e4344280-24db-11eb-83d0-9c33eb75f626.png)
![image](https://user-images.githubusercontent.com/74270857/98880471-eac2ba00-24db-11eb-936a-7627a63ebac1.png)
![image](https://user-images.githubusercontent.com/74270857/98880480-ef876e00-24db-11eb-9304-fb09ccbe74dd.png)

Regards

**Comment by a3ilson** [comment]
@an0wak - Please make sure your templates were loaded prior to sending logs.  I've provided a screenshot of what it should look like but if the index pattern refers to logstash-* then you sent and received logs prior to the template and will need to remove and reload those templates.  Additionally, you'll also need to delete all related indices.


Legacy Index Template Example:
![Capture](https://user-images.githubusercontent.com/16884679/98891841-093d9c80-246d-11eb-9b0e-23cbfa580450.PNG)

**Comment by an0wak** [comment]
Really sorry for being naive, I'm new to ELK stack. 
I have the following under my Index Management although I don't quite follow what you mean "if the index pattern refers to logstash-* then you sent and received logs prior to the template and will need to remove and reload those templates"

I have some reference of logstach-* - highlighted in red.

![image](https://user-images.githubusercontent.com/74270857/98904186-46f20200-250d-11eb-86ef-14efce0ec44a.png)

Are you saying that since I was sending logs from OPNsense prior to setting up the templates it's stuffed things up?
And now I need to delete all the Legacy index templates and then go into Indices and delete all of those as well? Do I also remove the Logstash one?

Kind Regards

**Comment by a3ilson** [comment]
Navigate to Kibana>>Discover. Then select pfelk-firewall-* and provide a screen shot.

Example:
![Capture](https://user-images.githubusercontent.com/16884679/98945629-c4435580-24c0-11eb-9798-5b6fd02427e4.PNG)

**Comment by a3ilson** [comment]
Additionally, can you run the `/etc/pfELK/error-data.sh` script which will generate a log file of your configuration and attach the output here.

**Comment by an0wak** [comment]
Hi @Andrew,

Here is the screenshot you asked for

![image](https://user-images.githubusercontent.com/74270857/98997055-fcfa3200-2587-11eb-9bf5-9c99b72cf92e.png)

I have no idea what is going on .... the systems been standing as it's been since I ran the script, with no changes and now all of a sudden I am getting some panels popping up. I do however get popup notifications "The data you are seeing might be incomplete or wrong" and "1 of 2 shards failed"

![image](https://user-images.githubusercontent.com/74270857/98997000-eb188f00-2587-11eb-8a09-6c007338d916.png)
![image](https://user-images.githubusercontent.com/74270857/98997754-210a4300-2589-11eb-8eed-4e3f17e2b4ee.png)
![image](https://user-images.githubusercontent.com/74270857/98997144-26b35900-2588-11eb-8817-01a7453d0723.png)
![image](https://user-images.githubusercontent.com/74270857/98997159-2ca93a00-2588-11eb-8b05-e5cecf10c9c1.png)
![image](https://user-images.githubusercontent.com/74270857/98997184-3894fc00-2588-11eb-863f-3001df7cbf78.png)

I've attached the error.pflek log.
[error.pfelk.log](https://github.com/3ilson/pfelk/files/5533345/error.pfelk.log)

Can't find anything exciting in any of the other outputs.

Appreciate the help!

**Comment by a3ilson** [comment]
In the Firewall dashboard, expand the time from the last 15 minutes to the last 3 hours.

**Comment by a3ilson** [comment]
I've reviewed your previous log file and didn't note any issues. The prior discover screenshot appears as though everything is working. However, there may be a issue with the templates and/or (most likely) the saved objects.

Give the following a try:
- [ ] Delete all Indices
  - Navigate to Stack Management>>Index Management 
  - Once deleted, let it run until the indices are rebuilt. Then navigate and check both (firewall/squid) dashboards

**Comment by an0wak** [comment]
Ok, I've deleted all the indices. 

Before deletion
![image](https://user-images.githubusercontent.com/74270857/99026806-f2f42580-25bf-11eb-9d76-db0e51f9dcb1.png)

After deletion - I noticed their health is still coming up as "Yellow"
![image](https://user-images.githubusercontent.com/74270857/99026953-3a7ab180-25c0-11eb-9ac3-9551530e7719.png)

If I look at the Stats I see the following successful 1 of 2 but no failed?
![image](https://user-images.githubusercontent.com/74270857/99027007-5aaa7080-25c0-11eb-9484-c65f1f188110.png)

Cheers

**Comment by a3ilson** [comment]
Ok, what does the dashboard look like?

**Comment by an0wak** [comment]
The dashboard looks Ok for the most part. I do have the following at the bottom. Not sure what this is....
![image](https://user-images.githubusercontent.com/74270857/99031432-2ee0b800-25cb-11eb-8074-6bce7bd776fc.png)

That should be right? 
One thing is there a top sites under the squid panel? or is this something I'd need to implement.

**Comment by a3ilson** [comment]
The error depicted above is indicative of a null value meaning there are no fields in which contain any data to populate.  I would expand your time frame and/or allow more time (log collection) to see if the issue still resides.

As for the a top sites element. There is not one  in the current dashboard but that is a fairly easy visualization to add/create - feel free to edit and add any desired visualizations/elements.

**Comment by an0wak** [comment]
Thanks Andrew!
