### ISSUE TITLE
logstash error and not listening on network

### ISSUE THREAD

**Issue by nullzeroroute** [pfelk/pfelk#256]
I installed today using the manual method to a Ubuntu 20.04.1 LTS server.  Kibana and Elasticsearch seem to start ok and are listening on the network, however logstash shows an error and is not listening on the network.  Restarting logstash doesn't seem to solve any issues.  Rebooting the server has not helped.  I intend to use this for pfSense.  The problem seems to be related to logstash, though I'm new to this so I have no idea really.  Any help is appreciated.

$ tail -f /var/log/logstash/logstash-plain.log
[2021-01-13T23:03:54,816][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`"}
[2021-01-13T23:03:54,897][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`>, :backtrace=>["org/logstash/execution/ConvergeResultExt.java:129:in `create'", "org/logstash/execution/ConvergeResultExt.java:57:in `add'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:378:in `block in converge_state'"]}
[2021-01-13T23:03:54,949][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
[2021-01-13T23:04:21,928][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.10.1", "jruby.version"=>"jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.8+10 on 11.0.8+10 +indy +jit [linux-x86_64]"}
[2021-01-13T23:04:30,857][INFO ][org.reflections.Reflections] Reflections took 59 ms to scan 1 urls, producing 23 keys and 47 values
[2021-01-13T23:04:32,147][ERROR][logstash.filters.grok    ] Unknown setting 'copy' for grok
[2021-01-13T23:04:32,167][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (ConfigurationError) Something is wrong with your configuration.", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:119)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:83)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1156)", "org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$initialize$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)", "org.jruby.RubyClass.newInstance(RubyClass.java:939)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:365)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:834)"]}
[2021-01-13T23:04:32,182][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`"}
[2021-01-13T23:04:32,304][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`>, :backtrace=>["org/logstash/execution/ConvergeResultExt.java:129:in `create'", "org/logstash/execution/ConvergeResultExt.java:57:in `add'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:378:in `block in converge_state'"]}
[2021-01-13T23:04:32,347][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

[20210113 error.pfelk.log](https://github.com/pfelk/pfelk/files/5812288/20210113.error.pfelk.log)

**Comment by revere521** [comment]
The error `An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle Java::JavaLang::IllegalStateExceptionforPipelineAction::Create>`  sometimes refers to something being caught in the config (something unconfigured or misconfigured). 

Looking at your error log, its balking at a 'copy' command in the filter; which is used in the squid section of the 05-apps.conf related to an IP address field. 

That might mean GeoIP (either native or MaxMind) is not enriching the data for ip addresses. 

so a couple of questions: 

First are you using Max Mind for GeoIP?
Second, did you complete all the configuration items in the guide: https://github.com/pfelk/pfelk/blob/master/install/configuration.md  ?

**Comment by a3ilson** [comment]
The only 'copy' instance, as @revere521 indicated, is in the 05-apps.conf file. However, this is specific to squid - can you elaborate more into your specific setup (i.e. are you running pfsense or opnsense, what version are you running and what logs are being sent?)

The 05-apps.conf file was amended removing the copy command - the change was incorporated within the GROK filter.  If you update your 05-apps.conf file and pfelk.grok to the latest version, I'd be curious if the problem persist.

By chance are you also the same person (Bắc Phạm Đức) who posted via YouTube - not looking to duplicate efforts troubleshooting.

**Comment by nullzeroroute** [comment]
I just put the 05 file in place and that worked, logstash is listening now!  

jim@homevmsrv1:/etc/logstash/conf.d$ sudo lsof -i | grep logstash
java      54958        logstash   85u  IPv6 209073      0t0  TCP localhost:53002->localhost:9200 (ESTABLISHED)
java      54958        logstash   89u  IPv6 209075      0t0  TCP localhost:53004->localhost:9200 (ESTABLISHED)
java      54958        logstash   90u  IPv6 209077      0t0  TCP localhost:53006->localhost:9200 (ESTABLISHED)
java      54958        logstash   91u  IPv6 209079      0t0  TCP localhost:53008->localhost:9200 (ESTABLISHED)
java      54958        logstash   92u  IPv6 209081      0t0  TCP localhost:53010->localhost:9200 (ESTABLISHED)
java      54958        logstash   93u  IPv6 209083      0t0  TCP localhost:53012->localhost:9200 (ESTABLISHED)
java      54958        logstash   94u  IPv6 209085      0t0  TCP localhost:53014->localhost:9200 (ESTABLISHED)
java      54958        logstash   95u  IPv6 209087      0t0  TCP localhost:53016->localhost:9200 (ESTABLISHED)
java      54958        logstash  105u  IPv6 209104      0t0  TCP *:5040 (LISTEN)
java      54958        logstash  112u  IPv6 209115      0t0  TCP *:5044 (LISTEN)
java      54958        logstash  113u  IPv4 209116      0t0  UDP *:5140
java      54958        logstash  114u  IPv4 209117      0t0  UDP *:5141
java      54958        logstash  115u  IPv4 209118      0t0  UDP *:5190
java      54958        logstash  127u  IPv6 209152      0t0  TCP localhost:9600 (LISTEN)
jim@homevmsrv1:/etc/logstash/conf.d$

I followed the manual method steps for the install and the configuration yesterday, as well as all of the configuration steps related to the server.  Prior to posting the report, I didn't make any other changes to the set up which are different from what's laid out in the manual install and configuration steps. I hadn't made any changes on the pfsense firewall, since it's apparent logstash wasn't listening yet.  I skipped the optional MaxMind set up step.  I haven't viewed the YouTube videos, so I've made no comments there.  

Is there any other info I can provide that might help isolate the problem I was experiencing further?

**Comment by revere521** [comment]
I think it was specifically related to the missing config file.  The java illegal state exception/pipeline errors in logstash usually refer to a module or a specific line in a conf file or grok patter that is broken. 

In a manual setup sometimes its easy to drop a character in copy/paste etc.  I have done it many times.

**Comment by a3ilson** [comment]
@nullzeroroute 
> I just put the 05 file in place and that worked, logstash is listening now!

So is it working now? The updated/amended 05-apps.conf and pfelk.grok fixed your issue?

**Comment by nullzeroroute** [comment]
The amended 05-apps.conf file corrected the issue, I actually didn't do anything with any other files.  Sorry I wasn't more clear.

In fact, I had gone through the entire set up two different times on two different hosts yesterday, both times had the exact same result, so I don't have any reason to believe there was a copy/paste issue.  Whatever changed in that amended file made the problem go away.

Thanks for your quick help!

**Comment by a3ilson** [comment]
@nullzeroroute - Great and thanks for your assistance in resolving this.  I believe it to be limited as my setup had the prior configuration but after going through, I noticed it was a redundant mutation and simply fixed within the grok filter making it a little bit more efficient and corrected the issue.
