### ISSUE TITLE
Empty Dashboards

### ISSUE THREAD

**Issue by jcollins313** [pfelk/pfelk#272]
**Describe the bug**
All dashboards are empty after installation via scrip method.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/36423807/108758532-d34e9080-7510-11eb-88d2-5cc565a57a11.png)

**Firewall System (please complete the following information):**
 - pfSense
 - Version 2.4.5-RELEASE-p1 (amd64)
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
Linux 5.4.0-65-generic x86_64
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 
 **Installation method (manual, ansible-playbook, docker, script):**
Script Install
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 - elasticsearch  7.11.0       amd64        Distributed RESTful search engine built for the cloud
 - kibana         7.11.0       amd64        Explore and visualize your Elasticsearch data
 - logstash       1:7.11.0-1   amd64        An extensible l
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
[2021-02-22T07:05:07,120][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.11.0-000001] from [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] in policy [kibana-event-log-policy]
[2021-02-22T07:05:07,147][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.ds-ilm-history-5-2021.02.22-000001] from [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] in policy [ilm-history-ilm-policy]
[2021-02-22T07:05:07,170][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.11.0-000001] from [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] in policy [kibana-event-log-policy]
[2021-02-22T07:05:07,193][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.ds-ilm-history-5-2021.02.22-000001] from [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] in policy [ilm-history-ilm-policy]
[2021-02-22T07:05:07,217][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.11.0-000001] from [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-index-color"}] in policy [kibana-event-log-policy]
[2021-02-22T07:05:07,240][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.ds-ilm-history-5-2021.02.22-000001] from [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-index-color"}] in policy [ilm-history-ilm-policy]
[2021-02-22T07:05:07,265][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.11.0-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-index-color"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [kibana-event-log-policy]
[2021-02-22T07:05:07,289][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.ds-ilm-history-5-2021.02.22-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-index-color"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [ilm-history-ilm-policy]
[2021-02-22T07:10:20,346][INFO ][o.e.c.m.MetadataCreateIndexService] [pfelk] [.async-search] creating index, cause [api], templates [], shards [1]/[0]
[2021-02-22T13:22:30,727][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-firewall-000001/u0Tej_L2T3aYEjs8kJg8eg] update_mapping [_doc]

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [logstash-input-tcp-6.0.6.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [logstash-input-tcp-6.0.6.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 0
        at org.logstash.beats.Protocol.version(Protocol.java:22) ~[logstash-input-beats-6.0.12.jar:?]
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:62) ~[logstash-input-beats-6.0.12.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[logstash-input-tcp-6.0.6.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[logstash-input-tcp-6.0.6.jar:?]
        ... 11 more
[2021-02-22T07:14:48,678][WARN ][logstash.codecs.line     ][pfelk][pfelk-suricata] Received an event that has a different character encoding than you configured. {:text=>"\\x80\\u0000\\u0000(\\tw)\\xD1\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0002\\u0000\\u0001\\x86\\xA0\\u0000\\u0000\\u0000\\u0002\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000", :expected_charset=>"UTF-8"}

 - Kibana logs (`journalctl -u kibana.service`)
-- Logs begin at Mon 2021-02-22 01:03:18 CST, end at Mon 2021-02-22 13:37:32 CST. --
Feb 22 06:56:26 pfelk systemd[1]: Started Kibana.
Feb 22 06:56:33 pfelk systemd[1]: Stopping Kibana...
Feb 22 06:56:35 pfelk systemd[1]: kibana.service: Succeeded.
Feb 22 06:56:35 pfelk systemd[1]: Stopped Kibana.
Feb 22 06:56:35 pfelk systemd[1]: Started Kibana.
[error.pfelk.log](https://github.com/pfelk/pfelk/files/6024762/error.pfelk.log)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
@jcollins313 - Thanks for providing sufficient information to troubleshoot this issue and apologizes for the inconvenience.

Please run the following TCPDUMP command, to confirm that you are receiving logs from pfSense:
```
sudo tcpdump -vvv -A -i any port 5141
```

If you are receiving logs, please provide a sampling, as I suspect that the revised GROK filter might not support pfSense versions prior to v2.5.0. We can amend the grok pattern, to get it working or you can replace line number 12 from 03-filter.conf with the following:
```
match => {"message" => "<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[observer][hostname]}\s+)?%{DATA:[process][name]}(?:\[%{POSINT:[process][pid]}\])?:%{SPACE}%{GREEDYDATA:filter_message}"}
```
That was the GROK pattern prior to pfSense 2.5.0 and was validate to work on OPNsense 21.2 and pfSense 2.5.0 (both formats).

**Comment by jcollins313** [comment]
- sudo tcpdump -vvv -A -i any port 5140
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
15:52:21.919373 IP (tos 0x0, ttl 64, id 30693, offset 0, flags [none], proto UDP (17), length 164)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 136
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:21 filterlog: 43,,,1000002663,vmx0,match,pass,out,4,0x0,,64,42584,0,none,17,udp,72,192.168.1.1,192.168.1.21,2004,53,52
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3231 2066 696c 7465 726c 6f67 3a20
        0x0020:  3433 2c2c 2c31 3030 3030 3032 3636 332c
        0x0030:  766d 7830 2c6d 6174 6368 2c70 6173 732c
        0x0040:  6f75 742c 342c 3078 302c 2c36 342c 3432
        0x0050:  3538 342c 302c 6e6f 6e65 2c31 372c 7564
        0x0060:  702c 3732 2c31 3932 2e31 3638 2e31 2e31
        0x0070:  2c31 3932 2e31 3638 2e31 2e32 312c 3230
        0x0080:  3034 2c35 332c 3532
E...w...@.~........ ......6V<134>Feb 22 15:52:21 filterlog: 43,,,1000002663,vmx0,match,pass,out,4,0x0,,64,42584,0,none,17,udp,72,192.168.1.1,192.168.1.21,2004,53,52
15:52:21.919453 IP (tos 0x0, ttl 64, id 39000, offset 0, flags [none], proto UDP (17), length 163)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 135
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:21 filterlog: 64,,,100000101,vmx0,match,pass,in,4,0x0,,128,56094,0,none,17,udp,83,192.168.1.21,193.0.9.10,55881,53,63
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3231 2066 696c 7465 726c 6f67 3a20
        0x0020:  3634 2c2c 2c31 3030 3030 3031 3031 2c76
        0x0030:  6d78 302c 6d61 7463 682c 7061 7373 2c69
        0x0040:  6e2c 342c 3078 302c 2c31 3238 2c35 3630
        0x0050:  3934 2c30 2c6e 6f6e 652c 3137 2c75 6470
        0x0060:  2c38 332c 3139 322e 3136 382e 312e 3231
        0x0070:  2c31 3933 2e30 2e39 2e31 302c 3535 3838
        0x0080:  312c 3533 2c36 33
E....X..@.^........ .......3<134>Feb 22 15:52:21 filterlog: 64,,,100000101,vmx0,match,pass,in,4,0x0,,128,56094,0,none,17,udp,83,192.168.1.21,193.0.9.10,55881,53,63
15:52:21.919708 IP (tos 0x0, ttl 64, id 5110, offset 0, flags [none], proto UDP (17), length 167)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 139
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:21 filterlog: 44,,,1000002761,vmx1,match,pass,out,4,0x0,,127,56094,0,none,17,udp,83,23.114.233.150,193.0.9.10,11968,53,63
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3231 2066 696c 7465 726c 6f67 3a20
        0x0020:  3434 2c2c 2c31 3030 3030 3032 3736 312c
        0x0030:  766d 7831 2c6d 6174 6368 2c70 6173 732c
        0x0040:  6f75 742c 342c 3078 302c 2c31 3237 2c35
        0x0050:  3630 3934 2c30 2c6e 6f6e 652c 3137 2c75
        0x0060:  6470 2c38 332c 3233 2e31 3134 2e32 3333
        0x0070:  2e31 3530 2c31 3933 2e30 2e39 2e31 302c
        0x0080:  3131 3936 382c 3533 2c36 33
E.......@.......... ......@.<134>Feb 22 15:52:21 filterlog: 44,,,1000002761,vmx1,match,pass,out,4,0x0,,127,56094,0,none,17,udp,83,23.114.233.150,193.0.9.10,11968,53,63
15:52:24.956393 IP (tos 0x0, ttl 64, id 5127, offset 0, flags [none], proto UDP (17), length 190)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 162
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:24 filterlog: 53,,,1770009282,vmx1,match,block,in,4,0x0,,239,26682,0,none,6,tcp,40,94.102.51.17,23.114.233.150,43003,6949,0,S,3820067465,,1024,,
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3234 2066 696c 7465 726c 6f67 3a20
        0x0020:  3533 2c2c 2c31 3737 3030 3039 3238 322c
        0x0030:  766d 7831 2c6d 6174 6368 2c62 6c6f 636b
        0x0040:  2c69 6e2c 342c 3078 302c 2c32 3339 2c32
        0x0050:  3636 3832 2c30 2c6e 6f6e 652c 362c 7463
        0x0060:  702c 3430 2c39 342e 3130 322e 3531 2e31
        0x0070:  372c 3233 2e31 3134 2e32 3333 2e31 3530
        0x0080:  2c34 3330 3033 2c36 3934 392c 302c 532c
        0x0090:  3338 3230 3036 3734 3635 2c2c 3130 3234
        0x00a0:  2c2c
E.......@.......... .......`<134>Feb 22 15:52:24 filterlog: 53,,,1770009282,vmx1,match,block,in,4,0x0,,239,26682,0,none,6,tcp,40,94.102.51.17,23.114.233.150,43003,6949,0,S,3820067465,,1024,,
15:52:25.977992 IP (tos 0x0, ttl 64, id 45228, offset 0, flags [none], proto UDP (17), length 164)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 136
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:25 filterlog: 43,,,1000002663,vmx0,match,pass,out,4,0x0,,64,50562,0,none,17,udp,71,192.168.1.1,192.168.1.21,7086,53,51
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3235 2066 696c 7465 726c 6f67 3a20
        0x0020:  3433 2c2c 2c31 3030 3030 3032 3636 332c
        0x0030:  766d 7830 2c6d 6174 6368 2c70 6173 732c
        0x0040:  6f75 742c 342c 3078 302c 2c36 342c 3530
        0x0050:  3536 322c 302c 6e6f 6e65 2c31 372c 7564
        0x0060:  702c 3731 2c31 3932 2e31 3638 2e31 2e31
        0x0070:  2c31 3932 2e31 3638 2e31 2e32 312c 3730
        0x0080:  3836 2c35 332c 3531
E.......@.F+....... ......*V<134>Feb 22 15:52:25 filterlog: 43,,,1000002663,vmx0,match,pass,out,4,0x0,,64,50562,0,none,17,udp,71,192.168.1.1,192.168.1.21,7086,53,51
15:52:25.978005 IP (tos 0x0, ttl 64, id 58741, offset 0, flags [none], proto UDP (17), length 172)
    _gateway.syslog > pfelk.5140: [udp sum ok] SYSLOG, length: 144
        Facility local0 (16), Severity info (6)
        Msg: Feb 22 15:52:25 filterlog: 44,,,1000002761,vmx1,match,pass,out,4,0xb8,,64,54168,0,none,17,udp,76,23.114.233.150,209.51.161.238,19759,123,56
        0x0000:  3c31 3334 3e46 6562 2032 3220 3135 3a35
        0x0010:  323a 3235 2066 696c 7465 726c 6f67 3a20
        0x0020:  3434 2c2c 2c31 3030 3030 3032 3736 312c
        0x0030:  766d 7831 2c6d 6174 6368 2c70 6173 732c
        0x0040:  6f75 742c 342c 3078 6238 2c2c 3634 2c35
        0x0050:  3431 3638 2c30 2c6e 6f6e 652c 3137 2c75
        0x0060:  6470 2c37 362c 3233 2e31 3134 2e32 3333
        0x0070:  2e31 3530 2c32 3039 2e35 312e 3136 312e
        0x0080:  3233 382c 3139 3735 392c 3132 332c 3536
E....u..@..Z....... ........<134>Feb 22 15:52:25 filterlog: 44,,,1000002761,vmx1,match,pass,out,4,0xb8,,64,54168,0,none,17,udp,76,23.114.233.150,209.51.161.238,19759,123,56
^C
6 packets captured
6 packets received by filter
0 packets dropped by kernel

 - sudo tcpdump -vvv -A -i any port 5141 (not the port from the instructions)
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
^C
0 packets captured
1 packet received by filter
0 packets dropped by kernel


Awesome that also explains why my old setup broke when I upgraded to 2.5.
You just fixed 2 issues for me with out trying :)

I 'm going to upgrade pfSense back to 2.5 and report back.

**Comment by a3ilson** [comment]
@jcollins313 - Excellent!  Hope it works out and looking forward to your response!

**Comment by jcollins313** [comment]
![image](https://user-images.githubusercontent.com/36423807/108781884-3bf93580-7530-11eb-95ec-2f323ebe6598.png)
Everything is working! I didn't know that this new config would only work for pfSense 2.5 and greater.

Thank you for your work on this project! I have learned a lot just by following this project over the years.
