### ISSUE TITLE
Logstash fails to start on new scripted install

### ISSUE THREAD

**Issue by shuang703** [pfelk/pfelk#298]
**Describe the bug**

logstash fails to start on a fresh install using scripted method

**To Reproduce**
1. Follow current scripted installation steps 
2. Logstash fails to start

**Screenshots**
logstash log:
```
[2021-04-16T19:39:22,350][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.12.0", "jruby.version"=>"jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.10+9 on 11.0.10+9 +indy +jit [linux-x86_64]"}
[2021-04-16T19:39:23,293][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

[2021-04-16T19:39:28,435][INFO ][org.reflections.Reflections] Reflections took 70 ms to scan 1 urls, producing 23 keys and 47 values
[2021-04-16T19:39:29,931][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,065][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01: Temporary failure in name resolution"}
[2021-04-16T19:39:30,075][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,086][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,093][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,099][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,105][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,108][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,110][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,115][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,118][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,123][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,127][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,130][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,134][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,138][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,142][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,144][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,148][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,151][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,155][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,159][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,162][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,164][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,168][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://es01:9200/]}}
[2021-04-16T19:39:30,171][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://es01:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://es01:9200/][Manticore::ResolutionFailure] es01"}
[2021-04-16T19:39:30,173][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://es01:9200"]}
[2021-04-16T19:39:30,181][INFO ][logstash.filters.geoip   ][pfelk] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2021-04-16T19:39:30,199][INFO ][logstash.filters.geoip   ][pfelk] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2021-04-16T19:39:30,533][ERROR][logstash.javapipeline    ][pfelk] Pipeline error {:pipeline_id=>"pfelk", :exception=>#<LogStash::Filters::Dictionary::DictionaryFileError: Translate: Missing or stray quote in line 1 when loading dictionary file at /etc/pfelk/databases/service-names-port-numbers.csv>, :backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1899:in `block in shift'", "org/jruby/RubyArray.java:1809:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1867:in `block in shift'", "org/jruby/RubyKernel.java:1442:in `loop'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1821:in `shift'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/csv_file.rb:20:in `block in read_file_into_dictionary'", "org/jruby/RubyIO.java:3511:in `foreach'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/csv_file.rb:18:in `read_file_into_dictionary'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:101:in `merge_dictionary'", "org/jruby/RubyMethod.java:131:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:66:in `load_dictionary'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:53:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:19:in `create'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/translate.rb:166:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/etc/pfelk/conf.d/01-inputs.conf", "/etc/pfelk/conf.d/02-types.conf", "/etc/pfelk/conf.d/03-filter.conf", "/etc/pfelk/conf.d/05-apps.conf", "/etc/pfelk/conf.d/20-interfaces.conf", "/etc/pfelk/conf.d/30-geoip.conf", "/etc/pfelk/conf.d/35-rules-desc.conf", "/etc/pfelk/conf.d/36-ports-desc.conf", "/etc/pfelk/conf.d/37-enhanced_user_agent.conf", "/etc/pfelk/conf.d/38-enhanced_url.conf", "/etc/pfelk/conf.d/45-cleanup.conf", "/etc/pfelk/conf.d/49-enhanced_private.conf", "/etc/pfelk/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x2288769c run>"}
[2021-04-16T19:39:30,535][INFO ][logstash.javapipeline    ][pfelk] Pipeline terminated {"pipeline.id"=>"pfelk"}
[2021-04-16T19:39:30,548][ERROR][logstash.agent           ] Failed to execute action {:id=>:pfelk, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<pfelk>, action_result: false", :backtrace=>nil}
[2021-04-16T19:39:30,600][INFO ][logstash.runner          ] Logstash shut down.
[2021-04-16T19:39:30,607][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.13.0.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.13.0.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]
```

contents of my /etc/pfelk/databases/service-names-port-numbers.csv same as https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/databases/service-names-port-numbers.csv

**Firewall System (please complete the following information):**
 - pfSense
 - Version 2.5
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 ```
Linux 5.4.0-65-generic x86_64
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 **Installation method (manual, ansible-playbook, docker, script):**
 script

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 ```ii  logstash       1:7.12.0-1   amd64        An extensible logging pipeline```

**Comment by a3ilson** [comment]
Thanks for providing sufficient information to troubleshoot. However, we may need additional info.

The error is specific to the 50-outputs.conf file where it is unable to connect to elasticsearch. Specifically, it cannot connect to http://es01.com:9200 but the 50-outputs.conf file points to http://localhost:9200 that file is also referenced in the script [here]( https://github.com/pfelk/pfelk/blob/850c80467405c10c2e1b2840ef4a254a0fb0023b/etc/pfelk/scripts/pfelk-installer.sh#L1047) which pulls this file via wget [here](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/50-outputs.conf). I suspect you have additional files contained within your setup.

Please provide the log file generated by the error-data.sh script

**Comment by shuang703** [comment]
Attached error.pfelk.log

[error.pfelk.log](https://github.com/pfelk/pfelk/files/6331123/error.pfelk.log)

**Comment by a3ilson** [comment]
Your 50-outputs.conf file does not match. It should be [this one](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/50-outputs.conf) which is the same that is referenced in the script.

Essentially, your instance (logstash) is attempting to connect to elasticsearch via http://es01>9200 which does not matach the script (line 1046) reference [here](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/50-outputs.conf) which defines elasticsearch: `hosts => ["http://localhost:9200"]` vs `hosts => ["http://es01:9200"]`

Amend your 50-outputs.conf file with this [one](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/50-outputs.conf) and restart logstash.

**Comment by shuang703** [comment]
Thank you - that seems to have fixed the elasticsearch connection issue, but it's still erroring out with the same pipeline error below.

```2021-04-18T16:58:35,214][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.12.0", "jruby.version"=>"jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.10+9 on 11.0.10+9 +indy +jit [linux-x86_64]"}
[2021-04-18T16:58:36,138][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-04-18T16:58:40,742][INFO ][org.reflections.Reflections] Reflections took 30 ms to scan 1 urls, producing 23 keys and 47 values
[2021-04-18T16:58:42,307][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,454][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,494][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,496][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,542][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,553][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,558][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,563][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,564][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,598][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,605][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,622][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,631][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,631][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,653][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,660][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,664][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,668][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,669][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,695][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,700][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,704][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,707][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,708][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,742][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,748][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,756][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,760][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,761][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,787][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,794][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,797][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,802][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,802][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,822][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,826][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,830][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,832][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,833][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,891][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,902][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,921][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,923][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,924][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,942][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:42,946][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:42,948][INFO ][logstash.outputs.elasticsearch][pfelk] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2021-04-18T16:58:42,952][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:42,955][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:42,957][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:42,984][INFO ][logstash.outputs.elasticsearch][pfelk] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2021-04-18T16:58:42,996][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:43,006][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2021-04-18T16:58:43,009][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2021-04-18T16:58:43,012][INFO ][logstash.outputs.elasticsearch][pfelk] ES Output version determined {:es_version=>7}
[2021-04-18T16:58:43,013][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-04-18T16:58:43,041][INFO ][logstash.outputs.elasticsearch][pfelk] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2021-04-18T16:58:43,131][ERROR][logstash.javapipeline    ][pfelk] Pipeline error {:pipeline_id=>"pfelk", :exception=>#<LogStash::Filters::Dictionary::DictionaryFileError: Translate: Missing or stray quote in line 1 when loading dictionary file at /etc/pfelk/databases/service-names-port-numbers.csv>, :backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1899:in `block in shift'", "org/jruby/RubyArray.java:1809:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1867:in `block in shift'", "org/jruby/RubyKernel.java:1442:in `loop'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/csv.rb:1821:in `shift'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/csv_file.rb:20:in `block in read_file_into_dictionary'", "org/jruby/RubyIO.java:3511:in `foreach'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/csv_file.rb:18:in `read_file_into_dictionary'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:101:in `merge_dictionary'", "org/jruby/RubyMethod.java:131:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:66:in `load_dictionary'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:53:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/dictionary/file.rb:19:in `create'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-translate-3.2.3/lib/logstash/filters/translate.rb:166:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/etc/pfelk/conf.d/01-inputs.conf", "/etc/pfelk/conf.d/02-types.conf", "/etc/pfelk/conf.d/03-filter.conf", "/etc/pfelk/conf.d/05-apps.conf", "/etc/pfelk/conf.d/20-interfaces.conf", "/etc/pfelk/conf.d/30-geoip.conf", "/etc/pfelk/conf.d/35-rules-desc.conf", "/etc/pfelk/conf.d/36-ports-desc.conf", "/etc/pfelk/conf.d/37-enhanced_user_agent.conf", "/etc/pfelk/conf.d/38-enhanced_url.conf", "/etc/pfelk/conf.d/45-cleanup.conf", "/etc/pfelk/conf.d/49-enhanced_private.conf", "/etc/pfelk/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x7c22be7d run>"}
[2021-04-18T16:58:43,132][INFO ][logstash.javapipeline    ][pfelk] Pipeline terminated {"pipeline.id"=>"pfelk"}
[2021-04-18T16:58:43,145][ERROR][logstash.agent           ] Failed to execute action {:id=>:pfelk, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<pfelk>, action_result: false", :backtrace=>nil}
[2021-04-18T16:58:43,211][INFO ][logstash.runner          ] Logstash shut down.
[2021-04-18T16:58:43,219][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.13.0.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.13.0.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]```

**Comment by a3ilson** [comment]
Try downloading the [service-names-port-numbers.csv](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/databases/service-names-port-numbers.csv) file again...I suspect your versions might be corrupt.

**Comment by shuang703** [comment]
Logstash is up and running after replacing all the .csv files - thank you for your help!
