### ISSUE TITLE
Not receiving logs

### ISSUE THREAD

**Issue by cparsell** [pfelk/pfelk#357]
**Describe the bug**
I've run the script, enabled remote logging on pfSense, and verified that data is being sent to the computer with pfelk installed on it on port 5140. The dashboard shows no data and the logstash logs seem to allude to it not being able to connect ("Attempted to send a bulk request but there are no living connections in the pool"). ELK Stack is new to me so I apologize for not being better at navigating this.

**To Reproduce**
1. Go to 'DHCP Dashboard'
2. Error on the right says this but seems like it is unrelated and just that I have not set up any security yet for this. I tried adding what it suggested "xpack.security.enabled: true" to elasticsearch.yml and that just caused the whole thing not to start back up. "Warning: 299 Elasticsearch-7.15.1-83c34f456ae29d60e94d886e455e6a3409bba9ed "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security.""
3. Besides that, there just isn't any data being displayed so I am guessing Logstash isn't able to push it to Elasticsearch.

**Screenshots**
![Screenshot_20211116_193012](https://user-images.githubusercontent.com/15009005/142129631-cfd6d280-07db-491a-8ff9-e1217200a65a.png)

**Firewall System (please complete the following information):**
 - pfSense 
 - Version 2.5.2
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 - Linux 5.14.0-9parrot1-amd64 x86_64
PRETTY_NAME="Parrot OS 5.0 (LTS)"
NAME="Parrot OS"
VERSION_ID="5.0"
VERSION="5.0 (LTS)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://community.parrotsec.org/"

 
 **Installation method (manual, ansible-playbook, docker, script):**
Script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
Elasticsearch 7.15.1
Logstash 1:7.15.1-1
Kibana 7.15.1

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - [2021-11-16T18:08:23,895][INFO ][o.e.i.g.DatabaseRegistry ] [vxlx-parrot] downloading geoip database [GeoLite2-ASN.mmdb] to [/tmp/elasticsearch-1115342283782823723/geoip-databases/WOX0lVizTtqpouUQm6aacA/GeoLite2-ASN.mmdb.tmp.gz]
[2021-11-16T18:08:23,895][INFO ][o.e.i.g.DatabaseRegistry ] [vxlx-parrot] downloading geoip database [GeoLite2-City.mmdb] to [/tmp/elasticsearch-1115342283782823723/geoip-databases/WOX0lVizTtqpouUQm6aacA/GeoLite2-City.mmdb.tmp.gz]
[2021-11-16T18:08:24,135][INFO ][o.e.i.g.DatabaseRegistry ] [vxlx-parrot] successfully reloaded changed geoip database file [/tmp/elasticsearch-1115342283782823723/geoip-databases/WOX0lVizTtqpouUQm6aacA/GeoLite2-ASN.mmdb]
[2021-11-16T18:08:24,137][INFO ][o.e.i.g.DatabaseRegistry ] [vxlx-parrot] successfully reloaded changed geoip database file [/tmp/elasticsearch-1115342283782823723/geoip-databases/WOX0lVizTtqpouUQm6aacA/GeoLite2-Country.mmdb]
[2021-11-16T18:08:24,162][INFO ][o.e.i.g.GeoIpDownloader  ] [vxlx-parrot] geoip database [GeoLite2-ASN.mmdb] is up to date, updated timestamp
[2021-11-16T18:08:24,258][INFO ][o.e.i.g.GeoIpDownloader  ] [vxlx-parrot] geoip database [GeoLite2-City.mmdb] is up to date, updated timestamp
[2021-11-16T18:08:24,389][INFO ][o.e.c.r.a.AllocationService] [vxlx-parrot] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[pfelk-firewall-000001][0], [pfelk-dhcp-000001][0], [pfelk-suricata-000001][0]]]).
[2021-11-16T18:08:24,438][INFO ][o.e.i.g.GeoIpDownloader  ] [vxlx-parrot] geoip database [GeoLite2-Country.mmdb] is up to date, updated timestamp
[2021-11-16T18:08:24,723][INFO ][o.e.i.g.DatabaseRegistry ] [vxlx-parrot] successfully reloaded changed geoip database file [/tmp/elasticsearch-1115342283782823723/geoip-databases/WOX0lVizTtqpouUQm6aacA/GeoLite2-City.mmdb]
[2021-11-16T18:38:07,691][INFO ][o.e.c.m.MetadataIndexTemplateService] [vxlx-parrot] adding index template [simulate_template_v0ojxqxeq0anzh5nf2kqhw] for index patterns [a_fake_index_pattern_that_wont_match_any_indices]

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - [2021-11-16T18:08:05,921][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
[2021-11-16T18:08:10,932][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
[2021-11-16T18:08:15,986][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
[2021-11-16T18:08:18,225][ERROR][logstash.outputs.elasticsearch][pfelk][c5dfcb7b1874a5c8ce0254ba32dee962fedf31a91402eb271a19d45ce926ae85] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>64}
[2021-11-16T18:08:19,265][ERROR][logstash.outputs.elasticsearch][pfelk][c5dfcb7b1874a5c8ce0254ba32dee962fedf31a91402eb271a19d45ce926ae85] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>64}
[2021-11-16T18:08:20,956][ERROR][logstash.outputs.elasticsearch][pfelk][c5dfcb7b1874a5c8ce0254ba32dee962fedf31a91402eb271a19d45ce926ae85] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>64}
[2021-11-16T18:08:21,000][WARN ][logstash.outputs.elasticsearch][pfelk] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
[2021-11-16T18:08:21,306][ERROR][logstash.outputs.elasticsearch][pfelk][c5dfcb7b1874a5c8ce0254ba32dee962fedf31a91402eb271a19d45ce926ae85] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>64}
[2021-11-16T18:08:25,306][ERROR][logstash.outputs.elasticsearch][pfelk][c5dfcb7b1874a5c8ce0254ba32dee962fedf31a91402eb271a19d45ce926ae85] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>64}
[2021-11-16T18:08:26,013][WARN ][logstash.outputs.elasticsearch][pfelk] Restored connection to ES instance {:url=>"http://localhost:9200/"}

 - Kibana logs (`journalctl -u kibana.service`)
-- Journal begins at Mon 2021-10-04 05:18:45 PDT, ends at Tue 2021-11-16 19:15:21 PST. --
Nov 16 17:43:21 vxlx-parrot systemd[1]: Started Kibana.
Nov 16 17:44:00 vxlx-parrot systemd[1]: Stopping Kibana...
Nov 16 17:44:00 vxlx-parrot systemd[1]: kibana.service: Succeeded.
Nov 16 17:44:00 vxlx-parrot systemd[1]: Stopped Kibana.
Nov 16 17:44:00 vxlx-parrot systemd[1]: kibana.service: Consumed 15.065s CPU time.
Nov 16 17:44:00 vxlx-parrot systemd[1]: Started Kibana.

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
I don't seem to find a file with that name. Please let me know if there is a specific location I should look. 

Any help is appreciated.

**Comment by cparsell** [comment]
I think I've fixed the log problem by changing pfSense's log message format to "syslog". Data now shows up.

This is amazing. Thank you for making this.

**Comment by a3ilson** [comment]
@cparsell - glad you were able to resolve and looking into correcting the grok filter for the default pfSense log output (BSD).

**Comment by cparsell** [comment]
It stopped working soon after it started.

Here is what logstash's log now outputs: 


at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
[2021-11-17T11:57:45,095][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2021-11-17T11:57:45,100][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.1", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2021-11-17T11:57:45,106][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.security.enabled" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:121:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `block in merge'", "org/jruby/RubyHash.java:1415:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:198:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:331:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:279:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:93:in `<main>'"]}
[2021-11-17T11:57:45,109][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
[2021-11-17T11:57:53,437][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2021-11-17T11:57:53,442][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.1", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2021-11-17T11:57:53,447][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.security.enabled" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:121:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `block in merge'", "org/jruby/RubyHash.java:1415:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:198:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:331:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:279:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:93:in `<main>'"]}
[2021-11-17T11:57:53,450][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]

**Comment by a3ilson** [comment]
how much ram do you have allocated?

you do not need to configure security and I would suggest confirm it works before doing so.

**Comment by cparsell** [comment]
The machine it's running on has 16gb. Do I need to allocate memory for it? I've installed using the script so it is not running on a Docker image.

**Comment by cparsell** [comment]
I've changed the two lines in /etc/logstash/jvm.options from 1g to 4g, as follows:

-Xms4g
-Xmx4g

I also did this for Elasticsearch/jvm.options (8g)

and added 'discovery.type: single-node' to etc/elasticsearch/elasticsearch.yml


Its still reporting the error:
[2021-11-17T12:27:16,073][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]


It is definitely using a log of RAM, as I understood it would. I will upgrade the machine to 32gb in order to avoid that issue. Let me know if this error indicates if that is likely the issue.

**Comment by a3ilson** [comment]
Got it...ram is sufficient but I would recommend doing a clean install, check to see if it works before adjusting and/or making changes. It should work after the install...

**Comment by cparsell** [comment]
Alright, will try that. Thanks.

**Comment by cparsell** [comment]
I've reinstalled and it's working now. I'll report back if it changes. Thank you again for taking the time to respond.

**Comment by cparsell** [comment]
A quick question regarding configuring security. I've tried looking this up elsewhere and couldn't find a clear answer. 

I am using this at home and do not plan on buying a license from Elastic. Is there any way to configure this so that it stops the messages about security? Or is that just a thing I'll have to put up with for using it without a paying for a license?

**Comment by a3ilson** [comment]
Are you referring to the "Your data is no secure" message? if So you can tick the "Don't show again" and then click dismiss.

or by turning it off by amending elasticsearch.yml with:
```xpack.security.enabled: false```

Alternatively you could also enable and configure.

**Comment by cparsell** [comment]
<img width="494" alt="Screen Shot 2021-11-17 at 2 45 02 PM" src="https://user-images.githubusercontent.com/15009005/142294611-6b40aeaa-0dfb-4017-8bce-b385e65c6111.png">

I get these messages (at least 10) upon loading any dashboard.

**Comment by a3ilson** [comment]
Ugh...7.15 added those annoying notifications. I am running it within a docker installation and was able to turn those off by adding this [     - xpack.security.enabled=false](https://github.com/pfelk/pfelk/blob/b89e55c1ad277dc93e325778f382158836751945/docker-compose.yml#L13) within my yml file. 

For the script and manual install, you'll need to edit the Elasticsearch.yml (/etc/elasticsearch/elasticsearch.yml) and add ```xpack.security.enabled: false```, once added simply restart elasticsearch (```sudo systemctl restart elasticsearch.service```)

**Comment by cparsell** [comment]
I did that and it caused the website to no longer load.  It would just say "License not found"

**Comment by cparsell** [comment]
Nevermind, this time it worked. ;P

**Comment by cparsell** [comment]
I noticed that the Firewall data calls my interface OPNSense. Its relatively minor but is there is a place in the configuration files that I can correct this to pfSense?

![Screenshot_20211118_215613](https://user-images.githubusercontent.com/15009005/142572725-5483c26c-bacc-42e4-933b-725556103253.png)

**Comment by a3ilson** [comment]
Those fields may be changed within the 02-types.conf file. Once charged, you’ll need to restart logstash, to take/update

**Comment by cparsell** [comment]
I started using the default Elastic IP instead of MaxMind GeoIP because I didn't have a license yet. Now I do. The script failed to download it so I installed it and configured it myself. I tried running the script so that pfelk knew this but it just deleted GeoIP. So I reinstalled it manually. Is there anything I need to do for Pfelk to be configured to use it?

**Comment by a3ilson** [comment]
The wiki page should help with getting maxmind configured:

https://github.com/pfelk/pfelk/wiki/How-To:-MaxMind-via-GeoIP-with-pfELK

**Comment by cparsell** [comment]
Thanks
