### ISSUE TITLE
Error in the logs

### ISSUE THREAD

**Issue by JeMunos** [pfelk/pfelk#40]
I'm receiving the following error when I run logstash. I'm not sure what the issue is as I am unable to locate any oddities in the files:
Any assistance would be appreciated. 

```
[2019-10-06T00:16:31,031][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.4.0"}
[2019-10-06T00:16:32,625][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, {, ,, ] at line 45, column 28 (byte 844) after filter {\n  if \"pf\" in [tags] {\n    grok {\n      match => [ \"message\" ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2584:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:153:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:26:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}
```

**Comment by JeMunos** [comment]
```
# 10-pf.conf
filter {
  if "pf" in [tags] {
    grok {
      match => [ "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}",
     "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" ]
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
    }
  }
}
```

**Comment by a3ilson** [comment]
@JeMunos,

Please provide your 01-inputs.conf, 05-syslog.conf and 10-pf.conf.  Although you  provided 10-pf.conf which is where the suspected/referenced error resides; it may be the result of a prior syntax error.

**Comment by JeMunos** [comment]
```
# 01-inputs.conf
#tcp syslog stream via 5140
input {
  tcp {
    type => "syslog"
    port => 5140
  }
}
#udp syslogs stream via 5140
input {
  udp {
    type => "syslog"
    port => 5140
  }
}
```

```
# 05-syslog.conf
filter {
  if [type] == "syslog" {
    #Adjust to match the IP address of pfSense or OPNSense
    if [host] =~ /192\.168\.22\.1/ {
      mutate {
        add_tag => ["pf", "Ready"]
      }
    }
    #To enable or ingest multiple pfSense or OPNSense instances uncomment the below section
    ##############################
    #if [host] =~ /172\.2\.22\.1/ {
    #  mutate {
    #    add_tag => ["pf-2", "Ready"]
    #  }
    #}
    ##############################
    if "Ready" not in [tags] {
      mutate {
        add_tag => [ "syslog" ]
      }
    }
  }
}
filter {
  if [type] == "syslog" {
    mutate {
      remove_tag => "Ready"
    }
  }
}
```

```
# 11-firewall.conf
filter {
  if "pf" in [tags] and [syslog_program] =~ /^filterlog$/ {
    grok {
      add_tag => [ "firewall" ]
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => [ "syslog_message", "%{PF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}",
                 "syslog_message", "%{PF_IPv4_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}",
                 "syslog_message", "%{PF_IPv6_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}"]
    }
    # Change interface as desired
      if [interface] =~ /^igb0$/ {
        mutate {
          add_tag => [ "WAN" ]
      }
    }
     # Change interface as desired
      if [interface] =~ /^igb1$/ {
        mutate {
          add_tag => [ "DEV" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^igb2$/ {
        mutate {
          add_tag => [ "DMZ" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^igb3$/ {
        mutate {
          add_tag => [ "LAN" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^lo0$/ {
        mutate {
          add_tag => [ "Link-Local" ]
      }
    }
    if [source][ip] {
      # Check if source.ip address is private.
      cidr {
        address => [ "%{[source][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[src_locality]" => "private" }
      }
      if ![src_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[source][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[source][geo]"
        }
        geoip {
         default_database_type => 'ASN'
         database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
         #cache_size => 5000
         source => "[source][ip]"
         target => "[source][as]"
       }
       mutate {
         rename => { "[source][as][asn]" => "[source][as][number]"}
         rename => { "[source][as][as_org]" => "[source][as][organization][name]"}
       }
      }
    }
    if [destination][ip] {
      # Check if destination.ip address is private.
      cidr {
        address => [ "%{[destination][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[dest_locality]" => "private" }
      }
      if ![dest_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[destination][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[destination][geo]"
        }
        geoip {
         default_database_type => 'ASN'
         database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
         #cache_size => 5000
         source => "[destination][ip]"
         target => "[destination][as]"
       }
       mutate {
         rename => { "[destination][as][asn]" => "[destination][as][number]"}
         rename => { "[destination][as][as_org]" => "[destination][as][organization][name]"}
       }
      }
    }
    mutate {
      add_field => { "[event][dataset]" => "firewall"}
      update => { "[network][direction]" => "%{[network][direction]}bound" }
      update => { "[network][type]" => "ipv%{[network][type]}" }
    }
  }
}
```

**Comment by JeMunos** [comment]
I was able to resolve the issue by modifying the 10-pf.conf file as follows:
```
# 10-pf.conf
filter {
  if "pf" in [tags] {
    grok {
      match => { "message" => ["%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}", "%{SYSLOGTIMESTAMP:syslog_timestamp} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"] }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
    }
  }
}
```

**Comment by a3ilson** [comment]
@JeMunos,

The 10-pf.conf file was updated to address this issue.  

Thanks for your assistance!
