### ISSUE TITLE
opnsense suricata _grokparsefailure

### ISSUE THREAD

**Issue by xpliz** [pfelk/pfelk#42]
I'm getting _grokparsefailure from opnsense suricata logs either in syslog or eve format. 

logstash-plain.log
```
[2019-10-09T12:04:56,936][WARN ][logstash.filters.grok    ][main] Grok regexp threw exception {:exception=>"Invalid FieldReference: ids_network[transport] :backtrace=>["org/logstash/ext/JrubyEventExtLibrary.java:87:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:365:in `handle'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:343:in `block in match_against_groks'", "(eval):15:in `block in compile_captures_func'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-grok-0.11.5/lib/grok-pure.rb:202:in `capture'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:343:in `block in match_against_groks'", "org/jruby/RubyArray.java:1800:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:339:in `match_against_groks'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:329:in `match'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:293:in `block in filter'", "org/jruby/RubyHash.java:1417:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:292:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162:in `block in multi_filter'", "org/jruby/RubyArray.java:1800:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:243:in `block in start_workers'"], :class=>"RuntimeError"}
[2019-10-09T12:04:56,936][WARN ][logstash.filters.grok    ][main] Grok regexp threw exception {:exception=>"Invalid FieldReference: ids_network[transport] :backtrace=>["org/logstash/ext/JrubyEventExtLibrary.java:87:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:365:in `handle'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:343:in `block in match_against_groks'", "(eval):15:in `block in compile_captures_func'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-grok-0.11.5/lib/grok-pure.rb:202:in `capture'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:343:in `block in match_against_groks'", "org/jruby/RubyArray.java:1800:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:339:in `match_against_groks'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:329:in `match'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:293:in `block in filter'", "org/jruby/RubyHash.java:1417:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.1.1/lib/logstash/filters/grok.rb:292:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162:in `block in multi_filter'", "org/jruby/RubyArray.java:1800:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:243:in `block in start_workers'"], :class=>"RuntimeError"}
```

Kibana discover
```
tags:pf, Suricata, _grokparsefailure @timestamp:Oct 9, 2019 @ 12:05:43.129 received_from:0.0.0.0 syslog_program:suricata syslog_timestamp:Oct 9 12:05:43 received_at:Oct 9, 2019 @ 12:05:43.129 syslog_hostname:OPNsense.localdomain type:syslog syslog_message:{"timestamp": "2019-10-09T12:05:43.134723+0200", "flow_id": 1763022386147449, "in_iface": "igb1", "event_type": "alert", "src_ip": "0.0.0.0", "src_port": 3872, "dest_ip": "0.0.0.0", "dest_port": 57274, "proto": "TCP", "alert": {"action": "allowed", "gid": 1, "signature_id": 2000334, "rev": 13, "signature": "ET P2P BitTorrent peer sync", "category": "Potential Corporate Privacy Violation", "severity": 1, "metadata": {"updated_at": ["2010_07_30"], "created_at": ["2010_07_30"]}}, "app_proto": "failed", "flow": {"pkts_toserver": 433, "pkts_toclient": 615, "bytes_toserver": 38268, "bytes_toclient": 581579, "start": "2019-10-09T11:06:22.897145+0200"}} event.original:<174>Oct 9 12:05:43 OPNsense.localdomain suricata[41807]: {"timestamp": "2019-10-09T12:05:43.134723+0200", "flow_id": 1763022386147449, "in_iface": "igb1", "event_type": "alert", "src_ip": "0.0.0.0", "src_port": 3872, "dest_ip": "0.0.0.0", "dest_port": 57274, "proto": "TCP", "alert": {"action": "allowed", "gid": 1, "signature_id": 2000334, "rev": 13, "signature": "ET P2P BitTorrent peer sync", "category": "Potential Corporate Privacy Violation", "severity": 1
tags:pf, Suricata, _grokparsefailure @timestamp:Oct 9, 2019 @ 12:05:43.129 received_from:0.0.0.0 ids_gen_id:1 syslog_program:suricata ids_desc:ET P2P BitTorrent peer sync syslog_timestamp:Oct 9 12:05:43 received_at:Oct 9, 2019 @ 12:05:43.129 ids_sig_id:2000334 syslog_hostname:OPNsense.localdomain ids_class:Potential Corporate Privacy Violation type:syslog syslog_message:[1:2000334:13] ET P2P BitTorrent peer sync [Classification: Potential Corporate Privacy Violation] [Priority: 1] {TCP} 0.0.0.0:3872 -> 0.0.0.0:57274 event.original:<173>Oct 9 12:05:43 OPNsense.localdomain suricata[41807]: [1:2000334:13] ET P2P BitTorrent peer sync [Classification: Potential Corporate Privacy Violation] [Priority: 1] {TCP} 0.0.0.0:3872 -> 0.0.0.0:57274 event.dataset:suricata event.module:suricata host:0.0.0.0 ids_sig_rev:13 ids_pri:1 @version:1 syslog_pid:41807 _id:Dyv7r20BTkRClDrURZzC _type:_doc _index:pf-2019.10.09 _score: -
```

IPs are scrubed with 0.0.0.0 for security reasons. Proper IPs are parsed to logs from opnsense.

**Comment by a3ilson** [comment]
@xpliz - the latest revisions address this issue.  It is advised you use suricata logs in the eve format.
